//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShaurmaLand.Shared.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShaurmaLand.Shared.Localizations.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address was not found..
        /// </summary>
        public static string AddressNotFoundException {
            get {
                return ResourceManager.GetString("AddressNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address couldn&apos;t be deleted..
        /// </summary>
        public static string AddressUnsuccessfulDeleteException {
            get {
                return ResourceManager.GetString("AddressUnsuccessfulDeleteException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address couldn&apos;t be updated.
        /// </summary>
        public static string AddressUnsuccessfulUpdateException {
            get {
                return ResourceManager.GetString("AddressUnsuccessfulUpdateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument can&apos;t be null..
        /// </summary>
        public static string ArgumentNullException {
            get {
                return ResourceManager.GetString("ArgumentNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something was wrong in request..
        /// </summary>
        public static string BadRequest {
            get {
                return ResourceManager.GetString("BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderNotFoundException.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order was not found..
        /// </summary>
        public static string OrderNotFoundException {
            get {
                return ResourceManager.GetString("OrderNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shaurma was not found..
        /// </summary>
        public static string ShaurmaNotFoundException {
            get {
                return ResourceManager.GetString("ShaurmaNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shaurma couldn&apos;t be deleted..
        /// </summary>
        public static string ShaurmaUnsuccessfulDeleteException {
            get {
                return ResourceManager.GetString("ShaurmaUnsuccessfulDeleteException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shaurma couldn&apos;t be updated..
        /// </summary>
        public static string ShaurmaUnsuccessfulUpdateException {
            get {
                return ResourceManager.GetString("ShaurmaUnsuccessfulUpdateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order couldn&apos;t be made..
        /// </summary>
        public static string UnsuccessfulOrderException {
            get {
                return ResourceManager.GetString("UnsuccessfulOrderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User was not found..
        /// </summary>
        public static string UserNotFoundException {
            get {
                return ResourceManager.GetString("UserNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User couldn&apos;t be deleted..
        /// </summary>
        public static string UserUnsuccessfulDeleteException {
            get {
                return ResourceManager.GetString("UserUnsuccessfulDeleteException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User coudn&apos;t be updated..
        /// </summary>
        public static string UserUnsuccessfulUpdateException {
            get {
                return ResourceManager.GetString("UserUnsuccessfulUpdateException", resourceCulture);
            }
        }
    }
}
